# Generated by Django 4.2.3 on 2023-07-12 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('nombre_classes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('TWIN', 'TWIN'), ('SE', 'SE'), ('SAE', 'SAE'), ('CLOUD', 'CLOUD'), ('DS', 'DS'), ('WIN', 'WIN'), ('SIM', 'SIM'), ('SLIM', 'SLIM'), ('GMIX', 'GMIX'), ('INFINI', 'INFINI')], max_length=20)),
                ('nombre_classes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.niveau')),
                ('options', models.ManyToManyField(to='Gestion.option')),
            ],
        ),
    ]
