# Generated by Django 4.1 on 2023-07-13 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_enseignant_roles'),
        ('Gestion', '0002_alter_option_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('nombre_heures', models.IntegerField()),
                ('competences', models.TextField()),
                ('nombre_ects', models.IntegerField()),
                ('fiche_module', models.FileField(upload_to='fichiers_modules/')),
                ('nombre_enseignants', models.IntegerField()),
                ('responsable_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.enseignant')),
            ],
        ),
    ]
