# Generated by Django 4.2.3 on 2023-07-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='roles',
            field=models.ManyToManyField(related_name='enseignants', to='users.role'),
        ),
    ]
