# Generated by Django 4.2.3 on 2023-07-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('administrateur', 'Administrateur'), ('coordinateur_unité_pédagogique', 'Coordinateur unité pédagogique'), ('enseignant', 'Enseignant'), ('coordinateur_des_projets', 'Coordinateur des projets'), ('responsable_option', 'Responsable option'), ('responsable_module', 'Responsable module')], max_length=50)),
                ('description', models.TextField()),
                ('charge_horaire', models.IntegerField()),
            ],
        ),
    ]
