# Generated by Django 4.1.10 on 2023-08-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_enseignant_est_enseignant'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='charge_horaire',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
