# Generated by Django 4.1 on 2023-07-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_role_est_enseignant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='est_enseignant',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='est_enseignant',
            field=models.BooleanField(default=False),
        ),
    ]
