# Generated by Django 4.1.10 on 2023-07-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('nombre_heures', models.IntegerField()),
                ('competences', models.TextField()),
                ('nombre_ects', models.IntegerField()),
                ('fiche_module', models.FileField(upload_to='fichiers_modules/')),
                ('nombre_enseignants', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('nombre_classes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('TWIN', 'TWIN'), ('SE', 'SE'), ('SAE', 'SAE'), ('CLOUD', 'CLOUD'), ('DS', 'DS'), ('WIN', 'WIN'), ('SIM', 'SIM'), ('SLIM', 'SLIM'), ('GAMIX', 'GAMIX'), ('INFINI', 'INFINI')], max_length=20)),
                ('nombre_classes', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
