# Generated by Django 4.2.3 on 2023-07-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='nom',
            field=models.CharField(choices=[('TWIN', 'TWIN'), ('SE', 'SE'), ('SAE', 'SAE'), ('CLOUD', 'CLOUD'), ('DS', 'DS'), ('WIN', 'WIN'), ('SIM', 'SIM'), ('SLIM', 'SLIM'), ('GAMIX', 'GAMIX'), ('INFINI', 'INFINI')], max_length=20),
        ),
    ]
